export const ROUTES = {
  HOME: '/',
  AUTH: {
    LOGIN: '/auth/sign-in',
    SIGNUP: '/auth/signup',
    FORGOT_PASSWORD: '/auth/forgot-password',
    RESET_PASSWORD: '/auth/reset-password',
    VERIFY_EMAIL: '/auth/verify-email',
    CALLBACK: '/auth/callback',
  },
  AGENT: {
    LANGUAGE: '/language',
    ASTROLOGY: '/astrology',
  },
  STUDENT: {
    DASHBOARD: '/student/dashboard',
    TEACHERS: '/student/consultants',
    AI_CHIROLOGIST: '/student/ai-chirologist',
    CHAT: '/student/chat',
    TEACHER_CHAT: (teacherId: string) => `/student/chat?teacherId=${teacherId}`,
    MEETINGS: '/student/meetings',
    HISTORY: '/student/history',
    SESSION_REPORT: '/student/session-report',
    SETTINGS: '/student/settings',
  },
  TEACHER: {
    DASHBOARD: '/consultant/dashboard',
    CHAT: '/consultant/chat',
    STUDENT_CHAT: (userId: string) => `/consultant/chat?userId=${userId}`,
    MEETINGS: '/consultant/meetings',
    SERVICES: '/consultant/services',
    CREATE_SERVICE: '/consultant/services/create',
    EDIT_SERVICE: (serviceId: string) => `/consultant/services/edit/${serviceId}`,
    SETTINGS: '/consultant/settings',
    BLOGS: '/consultant/blogs',
    CREATE_BLOG: '/consultant/blogs/create',
    EDIT_BLOG: (blogId: string | number) => `/consultant/blogs/edit/${blogId}`,
    ASTROLOGY_STUDENTS: '/consultant/astrology-students',
  },
  AI_SESSION: {
    ROOT: '/ai-session',
    START: '/ai-session/start',
    SETUP: '/ai-session/setup',
  },
};
